### ISSUE TITLE
Link for "Verb SRL" and "Nominal SRL" not found

### ISSUE THREAD

**Issue by Yarkona** [veronica320/Zeroshot-Event-Extraction#1]
Hi~,
 the links of "Verb SRL" and  "Nominal SRL" are not found in github. 
Could you please share the two repos by google drive?

**Comment by veronica320** [comment]
Oops, I didn't realize that the SRL repos are still in private. I'll reach out to their authors and see if they can make it public. Sorry about the inconvenience!

**Comment by veronica320** [comment]
Link updated.

**Comment by Yarkona** [comment]
Thank you a lot!
